<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ApplicationId>com.loopayeh.pkgsender</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>
    <SupportedOSPlatformVersion>26</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="logo.png" />
    <EmbeddedResource Include="pkg-receiver.elf" />
    <AndroidResource Include="Resources\drawable\logo.png" />
    <ProjectReference Include="..\LoopDPI.Core\LoopDPI.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Xamarin.Google.Android.Material" Version="1.12.0.2" />
  </ItemGroup>
</Project>
